info:
  namespace: chinesestyle
recipes:
  # 合成台配方
  crafting_table: 
    # 竹简
    bamboo_slips: 
      enabled: true
      pattern:
        - XXX 
        - BBB
        - SSS
      pattern_2: 
        - BBB
        - SSS
        - XXX
      ingredients:
        S: STRING
        B: BAMBOO
      result: 
        item: chinesestyle:bamboo_slips 
        amount: 1
    # 铜镜
    bronze_mirror:
      enabled: true
      pattern:
      - XSX
      - SBS
      - XSX
      ingredients:
        S: STICK
        B: COPPER_INGOT
      result:
        item: chinesestyle:bronze_mirror
        amount: 1
    # 木凳
    stool:
      enabled: true
      pattern:
        - PPP
        - SXS
        - SXS
      ingredients:
        S: STICK
        P: SPRUCE_PLANKS
      result:
        item: chinesestyle:stool
        amount: 1
    # 椅子
    chair:
      enabled: true
      pattern:
        - MXX
        - MCM
        - MXM
      pattern_2:
        - XXM
        - MCM
        - MXM
      ingredients:
        M: MANGROVE_PLANKS
        C: chinesestyle:cushion
      result:
        item: chinesestyle:chair
        amount: 1
    # 坐垫
    cushion:
      enabled: true
      pattern:
        - WW
        - WW
      ingredients:
        W: WHEAT
      result:
        item: chinesestyle:cushion
        amount: 1
    # 青花瓷大椅子
    porcelain_grand_master_chair:
      enabled: true
      pattern:
        - MXX
        - MTM
        - MXM
      pattern_2:
        - XXM
        - MTM
        - MXM
      ingredients:
        T: LIGHT_GRAY_GLAZED_TERRACOTTA
        M: MANGROVE_PLANKS
      result:
        item: chinesestyle:porcelain_grand_master_chair
        amount: 1
    # 椅子
    chair_1:
      enabled: true
      pattern:
        - MXX
        - HHH
        - SXS
      pattern_2:
        - XXM
        - HHH
        - SXS
      ingredients:
        H: MANGROVE_SLAB
        M: MANGROVE_PLANKS
        S: STICK
      result:
        item: chinesestyle:chair_1
        amount: 1
    # 椅子
    chair_2:
      enabled: true
      pattern:
        - MXX
        - MTM
        - MMM
      pattern_2:
        - XXM
        - MTM
        - MMM
      ingredients:
        T: BAMBOO_MOSAIC
        M: MANGROVE_PLANKS
      result:
        item: chinesestyle:chair_2
    # 青花瓷碗
    blue_and_white_porcelain_bowl:
      enabled: true
      pattern:
      - XXX
      - XBX
      - QMQ
      pattern_2:
      - XBX
      - QMQ
      - XXX
      ingredients:
        M: MUD
        B: LAPIS_LAZULI
        Q: QUARTZ_BLOCK
      result:
        item: chinesestyle:blue_and_white_porcelain_bowl
        amount: 1
    # 青花瓷大瓶（带纸的那个）
    blue_and_white_porcelain_vase:
      enabled: true
      pattern:
      - XPX
      - QBQ
      - MMM
      ingredients:
        M: MUD
        B: LAPIS_LAZULI
        Q: QUARTZ_BLOCK
        P: PAPER
      result:
        item: chinesestyle:blue_and_white_porcelain_vase
        amount: 1
    # 青花瓷瓶
    blue_and_white_porcelain_vase_1:
      enabled: true
      pattern:
      - QXQ
      - MBM
      - MMM
      ingredients:
        M: MUD
        B: LAPIS_LAZULI
        Q: QUARTZ_BLOCK
      result:
        item: chinesestyle:blue_and_white_porcelain_vase_1
        amount: 1
    # 青花瓷罐
    blue_and_white_porcelain_pot:
      enabled: true
      pattern:
      - XXX
      - QBQ
      - MMM
      ingredients:
        M: MUD
        B: LAPIS_LAZULI
        Q: QUARTZ_BLOCK
      result:
        item: chinesestyle:blue_and_white_porcelain_pot
        amount: 1
    # 青花瓷罐（带盖子的那个）
    blue_and_white_porcelain_pot_1:
      enabled: true
      pattern:
      - XBX
      - QBQ
      - MMM
      ingredients:
        M: MUD
        B: LAPIS_LAZULI
        Q: QUARTZ_BLOCK
      result:
        item: chinesestyle:blue_and_white_porcelain_pot_1
        amount: 1
    # 锅炉（关）
    boiler_closed:
      enabled: true
      pattern:
      - BBB
      - BFB
      - BXB
      ingredients:
        B: chinesestyle:blue_brick
        F: FURNACE
      result:
        item: chinesestyle:boiler_closed
        amount: 1
    # 锅炉（开）
    boiler_open:
      enabled: true
      pattern:
      - BBB
      - BFB
      - BXB
      ingredients:
        B: chinesestyle:blue_brick
        F: FURNACE
        X: BLAZE_ROD
      result:
        item: chinesestyle:boiler_open
        amount: 1
    # 靴子
    boots:
      enabled: true
      shapeless: true # 无序合成
      ingredients:
        A: LEATHER_BOOTS
        B: HONEYCOMB
      result:
        item: chinesestyle:boots
        amount: 1
    # 中式书本
    chinese_book:
      enabled: true
      shapeless: true # 无序合成
      ingredients:
        A: BOOK
        B: BLUE_DYE
        C: STRING
      result:
        item: chinesestyle:chinese_book
        amount: 1
    # 书堆
    pile_of_books:
      enabled: true
      pattern:
        - AA
        - AX
      ingredients:
        A: chinesestyle:chinese_book
      result:
        item: chinesestyle:pile_of_books
        amount: 2
    # 中式立灯
    chinese_standing_lamp:
      enabled: true
      pattern:
      - PPP
      - PLP
      - SSS
      ingredients:
        P: PAPER
        L: LANTERN
        S: STICK
      result:
        item: chinesestyle:chinese_standing_lamp
        amount: 1
    # 玉玺
    imperial_jade_seal:
      enabled: true
      pattern:
      - XGX
      - XDX
      - XDX
      pattern_2:
      - XXG
      - XXD
      - XXD
      pattern_3:
      - GXX
      - DXX
      - DXX
      ingredients:
        G: GOLD_INGOT
        D: DIAMOND
      result:
        item: chinesestyle:imperial_jade_seal
        amount: 1  
    # 果盒
    fruit_box:
      enabled: true
      pattern:
        - AAA
        - PPP
      ingredients:
        A: APPLE
        P: SPRUCE_PLANKS
      result:
        item: chinesestyle:fruit_box
        amount: 1
    # 长桌边
    long_table_edge:
      enabled: true 
      pattern:
       - MMM
       - SXX
       - SXX
      pattern_2:
       - MMM
       - XXS
       - XXS
      ingredients:
        M: MANGROVE_SLAB
        S: STICK
      result:
        item: chinesestyle:long_table_edge
        amount: 1
    # 长桌中
    long_table_middle:
      enabled: true
      pattern:
        - MMM
        - XXX
        - XXX
      ingredients:
        M: MANGROVE_SLAB
      result:
        item: chinesestyle:long_table_middle
        amount: 1
    # 桌子1
    table_1:
      enabled: true 
      pattern:
        - MM
        - SS
        - SS
      ingredients:
        M: MANGROVE_SLAB
        S: STICK
      result:
        item: chinesestyle:table_1
        amount: 1
    # 桌子2
    table_2:
      enabled: true 
      pattern:
        - MXM
        - SXS
        - SXS
      ingredients:
        M: MANGROVE_SLAB
        S: STICK
      result:
        item: chinesestyle:table_2
        amount: 1
    # 蜡烛
    candle:
      enabled: true 
      pattern:
        - C
        - B
      ingredients:
        C: BROWN_CANDLE
        B: MANGROVE_BUTTON
      result:
        item: chinesestyle:candle
        amount: 1
    # 靠枕
    pillow:
      enabled: true
      shapeless: true # 无序合成
      ingredients:
        A: chinesestyle:cushion
      result:
        item: chinesestyle:pillow
        amount: 1
    # 麻袋
    sack:
      enabled: true
      pattern:
        - WPW
        - WWW
      ingredients:
        W: WHEAT
        P: POTATO
      result:
        item: chinesestyle:sack
        amount: 1
    # 布袋
    cloth_bag:
      enabled: true
      pattern:
        - WW
        - WW
      ingredients:
        W: WHEAT
      result: 
        item: chinesestyle:cloth_bag
        amount: 1
    # 大腿肉
    thigh_meat:
      enabled: true
      pattern:
        - M
        - P
      ingredients: 
        M: COOKED_PORKCHOP
        P: OAK_SLAB
      result:
        item: chinesestyle:thigh_meat
        amount: 1
    # 鱼肉
    fish:
      enabled: true 
      pattern:
        - F
        - P
      ingredients:
        F: COOKED_SALMON
        P: OAK_SLAB
      result:
        item: chinesestyle:fish
        amount: 1
    # 胡萝卜
    carrots:
      enabled: true
      shapeless: true # 无序合成
      ingredients:
        A: CARROT
        B: CARROT
      result:
        item: chinesestyle:carrots
    # 香炉
    incense_burner:
      enabled: true
      pattern:
      - CXC
      - CDC
      - CCC
      ingredients:
        C: COPPER_INGOT
        D: SAND
      result: 
        item: chinesestyle:incense_burner
        amount: 1
    # 香炉（带香）
    incense_burner_with_incense:
      enabled: true
      pattern:
      - CXC
      - CDC
      - CCC
      ingredients:
        C: COPPER_INGOT
        D: SAND
        X: END_ROD
      result: 
        item: chinesestyle:incense_burner_with_incense
        amount: 1
    # 长枕头
    long_pillow:
      enabled: true
      pattern:
      - YRY
      - WWW
      - YRY
      ingredients:
        Y: YELLOW_DYE
        R: RED_DYE
        W: WHITE_WOOL
      result: 
        item: chinesestyle:long_pillow
        amount: 1
    # 笔具
    pen_holder:  
        enabled: true  
        pattern:  
        - SSS  
        - SBS  
        - SWS  
        ingredients:  
          S: STICK 
          B: BAMBOO 
          W: WHITE_WOOL 
        result:  
          item: chinesestyle:pen_holder  
          amount: 1
    # 日晷
    sundial:
        enabled: true  
        pattern:  
        - SSS  
        - SIS  
        - SSS  
        ingredients:  
          S: STONE 
          I: IRON_BARS
        result:  
          item: chinesestyle:sundial  
          amount: 1
    # 小红灯笼
    little_red_lantern:
        enabled: true  
        pattern:  
        - XSX  
        - RTR  
        - RRR  
        ingredients:  
          R: RED_WOOL
          T: TORCH
          S: STICK 
        result:  
          item: chinesestyle:little_red_lantern
          amount: 1
    # 刀
    knife:
        enabled: true  
        pattern:  
        - XXI  
        - XIX  
        - SXX  
        ingredients:  
          I: IRON_INGOT
          S: STICK 
        result:  
          item: chinesestyle:knife
          amount: 1
    # 尺子
    ruler:
        enabled: true  
        pattern:  
        - XXS  
        - XSX  
        - SXX  
        ingredients:  
          S: STICK 
        result:  
          item: chinesestyle:ruler
          amount: 1
    # 草帽
    straw_hat:
        enabled: true  
        pattern:  
        - WWW  
        - WLW  
        - XXX  
        ingredients:  
          L: LEATHER_HELMET 
          W: WHEAT
        result:  
          item: chinesestyle:straw_hat
          amount: 1
    # 扫帚
    broom:
        enabled: true  
        pattern:  
        - XXS  
        - XSX  
        - WXX 
        ingredients:  
          S: STICK 
          W: WHEAT
        result:  
          item: chinesestyle:broom
          amount: 1
    # 绿豆糕
    mung_bean_cake:
        enabled: true  
        pattern:  
        - XXB  
        - XXW  
        - XXD
        ingredients:  
          B: BREAD
          W: WHEAT_SEEDS
          D: DARK_OAK_PRESSURE_PLATE
        result:  
          item: chinesestyle:mung_bean_cake
          amount: 1
    # 灵位
    spiritual_figure:
        enabled: true  
        pattern:  
        - SSS  
        - XDX  
        - OOO 
        ingredients:  
          S: STICK 
          D: DARK_OAK_TRAPDOOR
          O: OAK_SLAB
        result:  
          item: chinesestyle:spiritual_figure
          amount: 1
    # 立灯
    standing_lamp:
        enabled: true  
        pattern:  
        - XAX  
        - XBX  
        - CBC 
        ingredients:  
          A: chinesestyle:chinese_standing_lamp
          B: STICK
          C: OAK_SLAB
        result:  
          item: chinesestyle:standing_lamp
          amount: 1
    # 石灯
    stone_lamp:
        enabled: true  
        pattern:  
        - SSS  
        - XLX  
        - XBX 
        ingredients:  
          S: STONE_BRICK_STAIRS
          L: LANTERN
          B: STONE_BRICKS
        result:  
          item: chinesestyle:stone_lamp
          amount: 1
    # 须弥石座
    sumi_stone_seat:
        enabled: true  
        pattern:  
        - XXX  
        - CCC  
        - XXX 
        ingredients:  
          C: CHISELED_TUFF_BRICKS
        result:  
          item: chinesestyle:sumi_stone_seat
          amount: 1
    # 茶框（空）
    tea_basket:
        enabled: true  
        pattern:  
        - BXB 
        - BXB  
        - BBB 
        ingredients:  
          B: BAMBOO      
        result:  
          item: chinesestyle:tea_basket
          amount: 1
      # 宋代窗
    song_dynasty_window:
        enabled: true  
        pattern:  
        - ABA  
        - BAB  
        - ABA 
        ingredients:  
          A: PAPER
          B: STICK      
        result:  
          item: chinesestyle:song_dynasty_window
          amount: 1
    # 宋代门
    song_dynasty_door:
        enabled: true  
        pattern:  
        - XAX
        - XBX
        - XXX
        ingredients:  
          A: chinesestyle:song_dynasty_window
          B: OAK_PLANKS      
        result:  
          item: chinesestyle:song_dynasty_door
          amount: 1
    # 窗（一格）
    window_1:
        enabled: true  
        pattern:  
        - AAA
        - ABA
        - AAA
        ingredients:  
          A: STICK
          B: PAPER      
        result:  
          item: chinesestyle:window_1
          amount: 1
    # 窗（两格）
    window_2:
        enabled: true  
        pattern:  
        - XAX
        - XAX
        - XXX
        ingredients:  
          A: chinesestyle:window_1
        result:  
          item: chinesestyle:window_2
          amount: 1
     # 青玉寿字勾云夔龙纹烛台
    jsapphire_longevity_word_gouyun_kui_dragon_pattern_candlestick:
        enabled: true  
        pattern:  
        - XAX
        - XBX
        - DCD
        ingredients:  
          A: candle
          B: BLOCK_OF_QUARTZ
          C: WHITE_GLAZED_TERRACOTTA
          D: GOLD_INGOT     
        result:  
          item: chinesestyle:sapphire_longevity_word_gouyun_kui_dragon_pattern_candlestick
          amount: 1 
  # 烧炼配方
  cooking: 
    blue_brick:
      enabled: true
      ingredient: 
        item: BRICKS 
      machines:
      - FURNACE 
      exp: 3 
      cook_time: 200 
      result: 
        item: chinesestyle:blue_brick
        amount: 1
      
